### ISSUE TITLE
SmartEditor Pages: Typical user errors

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/cammIntegrationPortal#22]
Sometimes the user doesn't know how to edit a page content correctly completely, because the user forget's/doesn't know that the same content must be edited in/for another additional market or server group, too.

That's why there should be an optional editor note visible in edit mode with a customizable text.
The editor note should be an attribute of the SmartEditor tag, e.g. 

``` html
<... editornote="Please always update in all languages and on intranet+extranet" ...>
```

**Comment by cmalbertschw** [comment]
This property has already been implemented (not by me) as "NoteForEditor".
