### ISSUE TITLE
CommonMarkEditor doesn't support target attribute on link creation on document insert

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/cammIntegrationPortal#24]
### The document insertion form shows as follows

![image](https://cloud.githubusercontent.com/assets/3033827/18993508/e1a8b0be-8723-11e6-814d-525dd6f37d37.png)
### There are 2 general options available
1. Hide the line with the dropdown box for the target attribute
2. CommonMark must support the syntax for adding additional link attributes
### For option 1

The data referenced by the token must transport additional details on which properties are supported/unsupported (e.g. in this case, target is NOT supported)
### For option 2, one or both of these points must see progress
- Further development is required, see Knagis/CommonMark.NET#101
- Maybe additional work on CommonMark specs is required, see 
  - https://talk.commonmark.org/t/links-with-attributes-like-target-class-etc/2246
  - https://talk.commonmark.org/t/multimarkdown-link-and-reference-image-attributes/1916
  - http://fletcher.github.io/MultiMarkdown-5/syntax.html#linkandimageattributes
  - http://stackoverflow.com/questions/4425198/markdown-target-blank
  - https://talk.commonmark.org/t/consistent-attribute-syntax/272/104

**Comment by cmalbertschw** [comment]
Now we fall back to HTML when target is given. Can this be closed?

**Comment by jochenwezel** [comment]
yes, it's solved by option 3 ;-)
