### ISSUE TITLE
Editor SmartUpload default location should default to current application

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/cammIntegrationPortal#30]
The SmartUpload location currently defaults to 
`/system/modules/smartwcms/`
and also to
`/sysdata/modules/smarteditor/`

but should better default to 
`~/system/se-webupload/` 
as it's currently deployed by NuGet package cammWM.SmartEditorUpload

Locations to change are at least:
- [x] Html-Resources (bug)
  ![image](https://cloud.githubusercontent.com/assets/3033827/19004274/72801b8c-8755-11e6-9915-94b0c08f213c.png)
- [x] Properties for UploadFormUrl (feature request)
- [ ] ...? (feature request)

**Comment by cmalbertschw** [comment]
> Properties for UploadFormUrl (feature request)

Already exists

**Comment by cmalbertschw** [comment]
No more occurrences found.
