### ISSUE TITLE
Data protection cleanup: Deleted users and minimal data

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/cammIntegrationPortal#31]
Data protection cleanup should keep a minimal amount of data, because some applications might refer to those user accounts: in case data protection is very aggressive and removes absolutely all user account data, an application might get a UserNotFoundException, but it must be e.g. a UserHasBeenDeletedException or empty user name/data (depending on lookup/search methods/arguments)

For this, there is the need to save some minimal data for all user accounts in log_users:
- [x] exiting+removed user accounts (e.g. by patch-sql: IsDeletedUser="0")
- [x] on-remove of user account: IsDeletedUser="1"
- [x] data protection setup page: never provide flag "IsDeletedUser" with a checkbox

**Comment by cmalbertschw** [comment]
> on-remove of user account: IsDeletedUser="1"

Basically already exists as "DeletedOn"

**Comment by jochenwezel** [comment]
Okay, so we should use "DeletedOn"! 👍

**Comment by jochenwezel** [comment]
Update: for compatibility reasons, we should use
IsDeletedUser="1" as well as DeletedOn=...

in case DeletedOn is available and IsDeletedUser is missing, IsDeletedUser should be interpreted as "1"
in case IsDeletedUser is available and DeletedOn is missing, DeletedOn should be interpreted as 1/1/1900
Caution: above double-check rule should never cause indefinite loop!

**Comment by cmalbertschw** [comment]
After discussion with JW, we concluded UserHasBeenDeletedException  is missing an use case.

**Comment by cmalbertschw** [comment]
> in case DeletedOn is available and IsDeletedUser is missing, IsDeletedUser should be interpreted as "1"
> in case IsDeletedUser is available and DeletedOn is missing, DeletedOn should be interpreted as 1/1/1900

This is probably only relevant to the applications using these flags instead of the core application, right? If so, ticket can be probably be closed.
