### ISSUE TITLE
SmartEditors: "+" in Text always dropped

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/cammIntegrationPortal#33]
![image](https://cloud.githubusercontent.com/assets/3033827/22160435/bb945bec-df45-11e6-8e5c-d59676e3470e.png)
will be shown in preview as
![image](https://cloud.githubusercontent.com/assets/3033827/22160452/d029d690-df45-11e6-8899-4836acac2858.png)
and when going back to edit mode, content is modified to
![image](https://cloud.githubusercontent.com/assets/3033827/22160479/ecdc5790-df45-11e6-9186-62a0cc240602.png)
(two space chars still available, but the plus char (+) ist missing, see yellow mark above)

**Comment by cmalbertschw** [comment]
Closed by 5417750f876f1aa5c6c8ed6482c82c119a42557e
