### ISSUE TITLE
Initial inner HTML of SmartEditors rendered as Html-Encoded

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/cammIntegrationPortal#35]
Following tag (no versions have been created, yet)
```asp.net
<cammWebEdit:SmartCommonMarkEditor marketlookupmode="0" 
			ID="MainEditor" runat="server">
<!-- initial text -->
<div>some text</div>
```

will be shown in client HTML encoded (But expected correct behaviour: HTML should be considered as HTML (not being encoded))
```text
<!-- initial text -->
<div>some text</div>
```

The deployed page source at client is as follows:
```html
&lt;!-- initial text --&gt;
&lt;div&gt;some text&lt;/div&gt;
```

**Comment by cmalbertschw** [comment]
Can't reproduce with current versions, it takes the HTML as it is and doesn't modify it.
