### ISSUE TITLE
Public user group ID 59 still shared between multiple server groups

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/cammIntegrationPortal#42]
![image](https://cloud.githubusercontent.com/assets/3033827/26575103/26d6344a-4524-11e7-80cc-ffe786f92854.png)
CORRECT: Anonymous group IS separated for each server group
WRONG/MISSING: Public group HAS TO BE separated for each server group, too

**Comment by cmalbertschw** [comment]
Hmm, I haven't found an instance where the public group isn't separated. When a new server group is created, a user group is added too (been this way since build 101). 

So overall it seems 59 is always assigned only to the initial server group.

**Comment by jochenwezel** [comment]
Not reproducable
