### ISSUE TITLE
After update from db b192, auto-rule auth is not protected

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/cammIntegrationPortal#46]
![image](https://user-images.githubusercontent.com/3033827/27626842-de82e6de-5be9-11e7-8968-304a7aaabcaf.png)
Action "Delete" is provided, but should not be deletable and marked as "Auto-Rule"

**Comment by cmalbertschw** [comment]
Can't be reproduced. It seems that already 79781dd1f571ff3e14a399501d25c6233329244e fixes this
