### ISSUE TITLE
Add app auth for user with Dev&Test fails if already authed without Dev&Test

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/cammIntegrationPortal#48]
User is already authorized with standard priviledge (no dev&test auth) and shall be assigned additionally with dev&test priviledge:
![image](https://user-images.githubusercontent.com/3033827/27859696-de39f4c0-6179-11e7-9655-20fe5c576dcf.png)

Expected: just add the dev&test auth

**Comment by cmalbertschw** [comment]
Appears to be already fixed in current/development verisons

**Comment by jochenwezel** [comment]
Maybe it appears only with older database patch version, e.g. 188 or 192 ?
