### ISSUE TITLE
Auth-Copy on deleting auth transmission

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/cammIntegrationPortal#49]
At http://server/sysdata/admin/apprights_delete_transmission.aspx:

![image](https://user-images.githubusercontent.com/3033827/28455701-3923e8e0-6e00-11e7-9f1b-b6f612b98a83.png)

and click on "Yes, delete it, but keep a copy of all inherited authorizations", following error appears:

![image](https://user-images.githubusercontent.com/3033827/28455654-10ff8ce8-6e00-11e7-90ef-e0c97271e849.png)

Environment:

Item | Version
-- | --
Base-Version | 4.12.209.106
Base Build | 209
Admin-Version | 4.12.209.106
Database Version | 4.10
Database Build | 188

**Comment by cmalbertschw** [comment]
Closed by 843dce71c95a727e35c9645334c5be8a6806bfbd
