### ISSUE TITLE
Logging module prevents login

### ISSUE THREAD

**Issue by svenclemens** [CompuMasterGmbH/cammIntegrationPortal#61]
If in whatever circumstances the database of the cammIntegrationPortal lacks free space there seems no possibility to login. The login would case a log message, which could not be saved (cause of insufficient space) and therefore will cause an error.

This is a major issue if the data which clog the database are log messages.
One cannot log in and so cannot lower the maximum retention days or the max entries.
Therefore the old or unneeded entries cannot be deleted and the login keeps broken.

**Comment by jochenwezel** [comment]
Project has been closed. Issue won't be fixed any more.
